### ISSUE TITLE
images coming in as code

### ISSUE THREAD

**Issue by tfraley** [barisusakli/nodebb-plugin-rss#10]
Good day, 

Must say love the idea of this plugin. And for some reason I thought it was working right last week, But seems to be off. Pulls the first thumbnail image fine but the images in the article comes out as code. 
You can find 4 examples here.  http://forum.lifewithtech.net:4567/category/9/lifewithtech-articles

Example this page 
http://forum.lifewithtech.net:4567/topic/4/how-was-your-favorite-company-rated

First image come in fine. However the secound image comes in as code                
![(http://static1.squarespace.com/static/52f6b5a9e4b086cbdc0cddd6/t/5582f232e4b0b72aab4a50c1/1434645046695/?format=1000w)

Any thoughts on how to fix this?

**Comment by barisusakli** [comment]
Can you try enabling the `collapseWhiteSpace` option from the plugins ACP page and see if it helps?

Not sure why the images after the first one are wrapped in <code> tags.

**Comment by tfraley** [comment]
Ok i've enabled collapsewhitespace. Does this only affect new posts? is there a way to force it to redo the ones in there?  I just chaned it to interval 1min and entries from 4-10 in hopes it posts more

**Comment by barisusakli** [comment]
It will only affect new posts the old ones you can fix my editing the post and remove the code markdown around the images.

**Comment by tfraley** [comment]
Yha not a problem fixing, But hate to make a post just to test. So ultimatly no way to test this outside of creating a new post..

**Comment by tfraley** [comment]
OK that seemed to fix it..

Testing, 
I removed the RSS add all togeather then removed each thread in the forum. 
Readded the RSS and it re-populated the thread

Looks like that collapsewhitespace fixed it. 

Thanks
