### ISSUE TITLE
Request: Longer intervals

### ISSUE THREAD

**Issue by tfraley** [barisusakli/nodebb-plugin-rss#13]
I would like to request longer intervals. 

We are using a few RSS's one in paticular has allot of posts. 
Could we maybe change this from a dropdown field to a custom field.
Maybe per hour. 

I would like to be able to set this fee once every other day or once a week even.

**Comment by Xuanwo** [comment]
Before the author do this change, you can update the code by yourself, change these place:

https://github.com/barisusakli/nodebb-plugin-rss/blob/master/index.js#L24-L27
