### ISSUE TITLE
Can't find the plugin in the admin 

### ISSUE THREAD

**Issue by ffmad** [barisusakli/nodebb-plugin-rss#14]
the route /admin/plugins/rss isn't working, rss plugin also not listed in the plugins list while activated

nodebb version : v0.8.2

**Comment by barisusakli** [comment]
What version of the plugin? Also what is your nodejs version

**Comment by ffmad** [comment]
node: 0.12.0, plugin version 0.2.18

**Comment by kidandcat** [comment]
Same error here

**Comment by vitasllc** [comment]
Yes sometimes that happened after reload nodeBB by admin interface!

Then full restart from linux shell
