### ISSUE TITLE
Some feeds do not pick up the Feed publish date instead they have date as "Invalid"

### ISSUE THREAD

**Issue by ghost** [barisusakli/nodebb-plugin-rss#36]
In the ACP you can set the feed time to feed published time & now, if you choose feed publish time for some feeds they come up as date: "Invalid", usually you want feed publish time, for instance a vendor news article with a event that happened in Nov 2016, you'd rather have it dated as Nov 2016 and not have the date set to the current time.

**Comment by barisusakli** [comment]
Can you post an example feed url that has this problem?
