### ISSUE TITLE
Some feeds appear with title(s) as "object Object"

### ISSUE THREAD

**Issue by zoureclipse** [barisusakli/nodebb-plugin-rss#38]
Some feeds which produce the rendered nodebb articles, appear with all titles are "object Object".
<img width="1222" alt="nodebb rssplugin titles" src="https://cloud.githubusercontent.com/assets/26046134/26273354/a525c456-3d26-11e7-9cdb-e8defd44ed95.png">

**Comment by barisusakli** [comment]
@zoureclipse can you post the url of the feed that has this problem?
