### ISSUE TITLE
Can't open the plugin in the ACP

### ISSUE THREAD

**Issue by ItzMeDwii** [barisusakli/nodebb-plugin-rss#46]
![image](https://user-images.githubusercontent.com/32206405/63635587-46faad80-c68e-11e9-931f-8fd2960b3a19.png)

Error msg: Cannot read property 'map' of undefined
NodeBB version:  v1.12.1

**Comment by barisusakli** [comment]
Check your log/output.log for any errors

**Comment by ItzMeDwii** [comment]
![image](https://user-images.githubusercontent.com/32206405/63648843-b1c7e980-c75f-11e9-940c-e7f726fc0859.png)


> Check your log/output.log for any errors

**Comment by barisusakli** [comment]
Which database are you using? Can you check the value stored at the key `nodebb-plugin-rss:feeds'? It should return an empty array if there is nothing but it seems like it returning undefined in your case.

Also put a console.log here to see what the return value is 
```
const feedUrls = await db.getSetMembers('nodebb-plugin-rss:feeds');
console.log('feedUrls', feedUrls);
const keys = feedUrls.map(url => 'nodebb-plugin-rss:feed:' + url);
```

**Comment by ItzMeDwii** [comment]
Im Using Redis.
![image](https://user-images.githubusercontent.com/32206405/63737589-2199b980-c8b1-11e9-93ec-05570441d76a.png)

**Comment by ItzMeDwii** [comment]
> Testing on redis I get `feedUrls []` What is your redis server version? Try with latest master to see if that works.

im using 5.0.3, can u teach me how to update the redis-server ?

**Comment by ItzMeDwii** [comment]
Im already use lastest redis server (5.0.5), but still cant open the plugin ACP...

**Comment by ItzMeDwii** [comment]
> Your redis version is fine, update your nodebb from 1.12.1 to latest master and it should work.

how to upgrade from 1.12.1 to master? im already folloingw the instruction at docs.nodebb.org, but im still stuck at 1.12.1.

**Comment by barisusakli** [comment]
```
./nodebb stop
git checkout master
git pull
./nodebb upgrade
./nodebb start 
```

**Comment by ItzMeDwii** [comment]
> ```
> ./nodebb stop
> git checkout master
> git pull
> ./nodebb upgrade
> ./nodebb start 
> ```

hmmmm
![image](https://user-images.githubusercontent.com/32206405/64107637-2e347b00-cda5-11e9-9ad2-95ff22d49b3a.png)

**Comment by ItzMeDwii** [comment]
> > ```
> > ./nodebb stop
> > git checkout master
> > git pull
> > ./nodebb upgrade
> > ./nodebb start 
> > ```
> 
> hmmmm
> ![image](https://user-images.githubusercontent.com/32206405/64107637-2e347b00-cda5-11e9-9ad2-95ff22d49b3a.png)

im already try that... but still

**Comment by ItzMeDwii** [comment]
ok thx :)
