### ISSUE TITLE
Tags for feeds not getting saved

### ISSUE THREAD

**Issue by pichalite** [barisusakli/nodebb-plugin-rss#7]
Adding a tag to existing feed or tags entered when adding a feed doesn't get saved along with the feed information.

Auto complete for "User"  field used to work in NodeBB v0.5.7. Doesn't seem to work from v0.6.0.

**Comment by barisusakli** [comment]
What version of the plugin are you using? I just fixed the user autocomplete and tags seem to work for me on version 0.2.4.

![image](https://cloud.githubusercontent.com/assets/2583394/5695991/bf4c494c-9989-11e4-9237-fe80cc1319c2.png)

**Comment by pichalite** [comment]
I am using v0.2.4 on NodeBB v0.6.0

**Comment by pichalite** [comment]
I see what I am doing wrong. I have to press enter after I type a tag. Found that out from the new post UI. May be "Press enter after each tag" should be part of the placeholder in the rss feed as well.
